### ISSUE TITLE
Names with Spaces

### ISSUE THREAD

**Issue by Haxley** [BuycraftPlugin/BuycraftPM#20]
Anyone know how to let players with spaces in their names purchase from the buycraft web store? Every time they type their name in it says that it’s not in the right format.

**Comment by uselesswaifu** [comment]
Use "" around their name!

**Comment by liam-wiltshire** [comment]
@Haxley names with spaces are supported in the pluigin - as @uselesswaifu suggested you will need to add "" around the username placeholder in your commands for it to work.

However, in order to get full XBL support for your webstore itself, you need to ensure you create a webstore using the "Minecraft" gametype (as opposed to the "Mincraft Offline" game type.

If you need any further help with this, please contact Buycraft support - support@buycraft.net
