### ISSUE TITLE
Synchronous CURL calls freeze the server for about 300ms every 3 minutes

### ISSUE THREAD

**Issue by CortexPE** [BuycraftPlugin/BuycraftPM#47]
https://github.com/BuycraftPlugin/BuycraftPM/blob/master/src/Buycraft/PocketMine/Execution/CategoryRefreshTask.php

**Comment by rjworks** [comment]
they don’t give a fuc* lmao, just write a shitty code and throw it in there

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
