### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by davidgamingzz** [BuycraftPlugin/BuycraftPM#53]
Buycraft causes my server to crash due to a segmentation fault. I suspect it's caused by Buycraft because it crashes my server while trying to check for due players. This also happens to a couple of my friends so I can safely say that this probably isn't caused by my other plugins. Please look into this, thank you and have a nice day :).

**Comment by rjworks** [comment]
+Tested and Confirmed

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
