### ISSUE TITLE
Can anyone help?

### ISSUE THREAD

**Issue by WoollenPanda275** [BuycraftPlugin/BuycraftPM#54]
I've recently set up the shop and now im testing if it all works but instead of it executing the command "2020-07-13 [11:49:57] [Server thread/INFO]: [Tebex-PMMP] Checking for existing of player with XUID (number) " gets spammed until i stop the server please help 😞

**Comment by efor89** [comment]
hi i have the same problem if i use cmd execute for offline player it work, but if i use only execute when the player is online and the player come online it spam in my console.

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
